name: test-linux-rebase

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  test-linux-rebase:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Rebase
      # this should really be the branch targetted by push request
        run: git rebase main
      - name: Test
        run: node test.js
