name: test-linux-no-rebase

on:
  pull_request:
    paths-ignore:
      - "README.md"
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  test-linux-no-rebase:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Test
        run: node test.js
